spring:
  application:
    name: zhaoj-backend-user-service
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  session:
    store-type: redis
    timeout: 2592000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/zhaoj
    username: zhaoj
    password: root
  redis:
    database: 1
    host: redis
    port: 6379
    timeout: 5000
  servlet:
    multipart:
      max-file-size: 10MB
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
server:
  address: 0.0.0.0
  port: 8102
  servlet:
    context-path: /api/user
    session:
      cookie:
        max-age: 2592000
        path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
codesandbox:
  type: remote
knife4j:
  enable: true
